export const helpCategories: { [key: string]: string } = {
  housing: "Housing",
  foodAndWater: "Food and Water",
  clothing: "Clothing",
  medicalAssistance: "Medical Assistance",
  transportation: "Transportation",
  petRescueAndCare: "Pet Rescue and Care",
  childcare: "Childcare",
  elderlyCare: "Elderly Care",
  volunteering: "Volunteering",
  donations: "Donations (Money or Goods)",
  searchAndRescue: "Search and Rescue",
  temporaryWork: "Temporary Work",
  counselingAndEmotionalSupport: "Counseling and Emotional Support",
  cleanupAndRepairs: "Cleanup and Repairs",
  legalAssistance: "Legal Assistance",
  communicationToolsAndDevices: "Communication Tools and Devices",
  relocationAssistance: "Relocation Assistance",
  shelterSupplies: "Shelter Supplies (Blankets, Tents, etc.)",
  generatorsAndPowerSupplies: "Generators and Power Supplies",
  vehicleAndEquipmentLending: "Vehicle and Equipment Lending",
  lostAndFound: "Lost and Found (People and Pets)",
  techSupport: "Tech Support (Access to WiFi, Phones, etc.)",
  evacuationAssistance: "Evacuation Assistance",
};
