export const dummyTasks: Task[] = [
  {
    id: "1",
    authorId: "123",
    authorName: "John Doe",
    authorAvatar: undefined,
    description: "Provide temporary housing for displaced families.",
    volunteersRequired: 5,
    volunteersAssigned: 3,
    applicants: ["user1", "user2", "user3"],
    status: "open",
    urgent: true,
    category: "housing",
    startDate: new Date("2025-01-12"),
    endDate: new Date("2025-01-15"),
  },
  {
    id: "2",
    authorId: "124",
    authorName: "Jane Smith",
    authorAvatar: undefined,
    description: "Distribute food and water to affected areas.",
    volunteersRequired: 10,
    volunteersAssigned: 7,
    applicants: ["user4", "user5"],
    status: "in_progress",
    urgent: false,
    category: "foodAndWater",
    startDate: new Date("2025-01-13"),
    endDate: new Date("2025-01-17"),
  },
  {
    id: "3",
    authorId: "125",
    authorName: "Alex Johnson",
    authorAvatar: undefined,
    description: "Collect donations for relief efforts.",
    volunteersRequired: 3,
    volunteersAssigned: 2,
    applicants: [],
    status: "open",
    urgent: false,
    category: "donations",
    startDate: new Date("2025-01-14"),
    endDate: new Date("2025-01-20"),
  },
  {
    id: "4",
    authorId: "123",
    authorName: "John Doe",
    authorAvatar: undefined,
    description: "Assist with pet rescue operations.",
    volunteersRequired: 4,
    volunteersAssigned: 1,
    applicants: ["user6"],
    status: "open",
    urgent: true,
    category: "petRescueAndCare",
    startDate: new Date("2025-01-15"),
    endDate: new Date("2025-01-18"),
  },
  {
    id: "5",
    authorId: "124",
    authorName: "Jane Smith",
    authorAvatar: undefined,
    description: "Help clean up debris in affected neighborhoods.",
    volunteersRequired: 6,
    volunteersAssigned: 3,
    applicants: ["user7", "user8", "user9"],
    status: "in_progress",
    urgent: false,
    category: "cleanupAndRepairs",
    startDate: new Date("2025-01-16"),
    endDate: new Date("2025-01-22"),
  },
  {
    id: "6",
    authorId: "125",
    authorName: "Alex Johnson",
    authorAvatar: undefined,
    description: "Provide legal assistance for disaster-related claims.",
    volunteersRequired: 2,
    volunteersAssigned: 1,
    applicants: ["user10"],
    status: "open",
    urgent: true,
    category: "legalAssistance",
    startDate: new Date("2025-01-17"),
    endDate: new Date("2025-01-19"),
  },
  {
    id: "7",
    authorId: "123",
    authorName: "John Doe",
    authorAvatar: undefined,
    description: "Set up WiFi and communication hubs.",
    volunteersRequired: 5,
    volunteersAssigned: 4,
    applicants: ["user11"],
    status: "completed",
    urgent: false,
    category: "communicationToolsAndDevices",
    startDate: new Date("2025-01-10"),
    endDate: new Date("2025-01-11"),
  },
  {
    id: "8",
    authorId: "124",
    authorName: "Jane Smith",
    authorAvatar: undefined,
    description: "Offer counseling sessions for disaster survivors.",
    volunteersRequired: 3,
    volunteersAssigned: 3,
    applicants: ["user12", "user13"],
    status: "in_progress",
    urgent: true,
    category: "counselingAndEmotionalSupport",
    startDate: new Date("2025-01-20"),
    endDate: new Date("2025-01-25"),
  },
  {
    id: "9",
    authorId: "125",
    authorName: "Alex Johnson",
    authorAvatar: undefined,
    description: "Donate and distribute blankets and tents.",
    volunteersRequired: 6,
    volunteersAssigned: 2,
    applicants: ["user14", "user15"],
    status: "open",
    urgent: false,
    category: "shelterSupplies",
    startDate: new Date("2025-01-22"),
    endDate: new Date("2025-01-28"),
  },
  {
    id: "10",
    authorId: "123",
    authorName: "John Doe",
    authorAvatar: undefined,
    description: "Transport generators to shelters.",
    volunteersRequired: 3,
    volunteersAssigned: 2,
    applicants: ["user16"],
    status: "open",
    urgent: true,
    category: "generatorsAndPowerSupplies",
    startDate: new Date("2025-01-23"),
    endDate: new Date("2025-01-24"),
  },
  {
    id: "11",
    authorId: "124",
    authorName: "Jane Smith",
    authorAvatar: undefined,
    description: "Organize a lost and found operation for people and pets.",
    volunteersRequired: 4,
    volunteersAssigned: 3,
    applicants: ["user17", "user18"],
    status: "completed",
    urgent: false,
    category: "lostAndFound",
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-01-05"),
  },
  {
    id: "12",
    authorId: "125",
    authorName: "Alex Johnson",
    authorAvatar: undefined,
    description: "Relocate families to safer zones.",
    volunteersRequired: 8,
    volunteersAssigned: 5,
    applicants: ["user19", "user20"],
    status: "in_progress",
    urgent: true,
    category: "relocationAssistance",
    startDate: new Date("2025-01-12"),
    endDate: new Date("2025-01-14"),
  },
  {
    id: "13",
    authorId: "123",
    authorName: "John Doe",
    authorAvatar: undefined,
    description: "Repair damaged homes and infrastructure.",
    volunteersRequired: 7,
    volunteersAssigned: 3,
    applicants: ["user21"],
    status: "open",
    urgent: false,
    category: "cleanupAndRepairs",
    startDate: new Date("2025-01-15"),
    endDate: new Date("2025-01-22"),
  },
  {
    id: "14",
    authorId: "124",
    authorName: "Jane Smith",
    authorAvatar: undefined,
    description: "Transport families to emergency shelters.",
    volunteersRequired: 10,
    volunteersAssigned: 6,
    applicants: ["user22", "user23"],
    status: "in_progress",
    urgent: true,
    category: "transportation",
    startDate: new Date("2025-01-16"),
    endDate: new Date("2025-01-20"),
  },
  {
    id: "15",
    authorId: "125",
    authorName: "Alex Johnson",
    authorAvatar: undefined,
    description: "Provide childcare services for displaced families.",
    volunteersRequired: 4,
    volunteersAssigned: 2,
    applicants: ["user24", "user25"],
    status: "open",
    urgent: false,
    category: "childcare",
    startDate: new Date("2025-01-18"),
    endDate: new Date("2025-01-25"),
  },
];
